"""The normaliser -- and the place where a project like this lies to itself.

Every rule added here makes the match rate go up.  That is precisely why each one
is declared as a first-class object with a rationale *and a stated risk*, why the
set is versioned, and why :func:`ablation` exists: the report shows the match
rate with each rule switched on in turn, so a reader can see exactly how many
matches each rule bought.  A rule that buys a great many matches is a rule to be
suspicious of, not proud of.

The governing distinction is spec §4.5:

* **Normalise** things that are *rendering*: how the text was wrapped, indented,
  encoded, and typeset for a fixed-width printer.
* **Never normalise** anything a diff would show a user: words, numbers,
  punctuation inside the operative text, cross-references, singular/plural,
  "shall"/"must".

Two numbers are always reported side by side -- ``exact`` (raw extracted text,
byte for byte) and ``normalized`` -- because a wide gap between them is the
signal that this file is doing too much work.
"""

from __future__ import annotations

import re
import unicodedata
from collections.abc import Callable
from dataclasses import dataclass

NORMALIZER_VERSION = "0.1.0"


@dataclass(frozen=True)
class Rule:
    key: str
    title: str
    rationale: str
    risk: str
    fn: Callable[[str], str]


# --- the rules ---------------------------------------------------------------


def _nfc(text: str) -> str:
    return unicodedata.normalize("NFC", text)


_QUOTE_MAP = str.maketrans(
    {
        "‘": "'",
        "’": "'",
        "‚": "'",
        "“": '"',
        "”": '"',
        "„": '"',
        "′": "'",
        "″": '"',
        "­": "",  # soft hyphen: a typesetting hint, never content
        "‑": "-",  # non-breaking hyphen
        "﻿": "",  # byte-order mark
    }
)


def _quotes(text: str) -> str:
    return text.translate(_QUOTE_MAP)


_WS_RE = re.compile(r"\s+")


def _whitespace(text: str) -> str:
    return _WS_RE.sub(" ", text).strip()


_SPACE_BEFORE_PUNCT_RE = re.compile(r"[ \t]+(?=[,;:.)\]])")


def _space_before_punct(text: str) -> str:
    return _SPACE_BEFORE_PUNCT_RE.sub("", text)


_SPACE_AFTER_OPEN_RE = re.compile(r"(?<=[(\[])[ \t]+")


def _space_after_open(text: str) -> str:
    return _SPACE_AFTER_OPEN_RE.sub("", text)


_DOUBLE_SPACE_SENTENCE_RE = re.compile(r"(?<=[.?!])\s{2,}")


def _sentence_spacing(text: str) -> str:
    return _DOUBLE_SPACE_SENTENCE_RE.sub(" ", text)


RULES: tuple[Rule, ...] = (
    Rule(
        key="N1",
        title="Unicode NFC",
        rationale=(
            "The two routes were generated by different toolchains and can encode "
            "the same accented character as a precomposed codepoint or as base + "
            "combining mark. NFC makes those one string."
        ),
        risk=(
            "None material. NFC is a canonical, information-preserving mapping; it "
            "cannot merge two characters that a reader would distinguish."
        ),
        fn=_nfc,
    ),
    Rule(
        key="N2",
        title="Straight quotes, drop soft hyphens and BOM",
        rationale=(
            "Curly quotes are typesetting. The compiled page and the printer view "
            "of an Act do not agree about them, and no statutory meaning turns on "
            "the direction of an apostrophe. Soft hyphens are line-break hints."
        ),
        risk=(
            "Low, but not zero: this is the one rule that touches characters "
            "inside the operative text. It maps quote glyphs onto each other and "
            "deletes only characters that have no printed width."
        ),
        fn=_quotes,
    ),
    Rule(
        key="N3",
        title="Collapse all whitespace to single spaces",
        rationale=(
            "The single most necessary rule. Both sources are fixed-width printer "
            "layouts that hard-wrap: the compiled ILCS page wraps at roughly 70 "
            "columns and the printer-friendly Act at roughly 60, so the *same* "
            "sentence carries newlines in different places. Paragraph indents are "
            "four non-breaking spaces in one layout and literal tabs in the other."
        ),
        risk=(
            "Real: it erases paragraph structure, so a genuine difference that "
            "consisted only of where a paragraph broke would be invisible. "
            "Accepted, because neither source's line breaks carry meaning -- they "
            "are artifacts of column width, and the two column widths differ."
        ),
        fn=_whitespace,
    ),
    Rule(
        key="N4",
        title="Remove whitespace before closing punctuation",
        rationale=(
            "An artifact of applying the amendment. A struck-through span in an "
            "enrolled Act consumes the space that joined it to the text around it, "
            "so deleting 'X <strike>Y</strike>, Z' leaves 'X , Z'. The compiled "
            "text says 'X, Z'."
        ),
        risk=(
            "Moderate, and it is the rule to watch. It is applied to both sides, "
            "so it can manufacture agreement. Its marginal contribution is "
            "measured in the ablation table; if it is large, that is a signal the "
            "strike-removal step needs fixing rather than papering over."
        ),
        fn=_space_before_punct,
    ),
    Rule(
        key="N5",
        title="Remove whitespace after opening bracket",
        rationale="The mirror of N4, from the same strike-removal artifact.",
        risk="Same as N4, and empirically much rarer.",
        fn=_space_after_open,
    ),
    Rule(
        key="N6",
        title="Single space after sentence-ending punctuation",
        rationale=(
            "Redundant once N3 is on; kept as a separate rule so the ablation can "
            "show it contributes nothing independently."
        ),
        risk="None once N3 is applied.",
        fn=_sentence_spacing,
    ),
)

RULES_BY_KEY = {r.key: r for r in RULES}
ALL_RULES = tuple(r.key for r in RULES)


def normalize(text: str, enabled: tuple[str, ...] | set[str] = ALL_RULES) -> str:
    """Apply the enabled rules, in declared order."""
    for rule in RULES:
        if rule.key in enabled:
            text = rule.fn(text)
    return text


def rules_table() -> str:
    """The rules, as a Markdown table for the report. Every rule, always."""
    lines = [
        "| Rule | What it does | Why it is a rendering difference, not a real one | Risk |",
        "|---|---|---|---|",
    ]
    for r in RULES:
        lines.append(f"| `{r.key}` | {r.title} | {r.rationale} | {r.risk} |")
    return "\n".join(lines)
